import java.text.SimpleDateFormat

plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = new SimpleDateFormat("dd.MM.yy").format(new Date())
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    maven {
        name = "Mojang"
        url = "https://libraries.minecraft.net/"
    }
    mavenLocal()
}

loom {
	//splitEnvironmentSourceSets()

	mods {
		"just-helper" {
			sourceSet sourceSets.main
			//sourceSet sourceSets.client
		}
	}

}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation ("net.kyori:adventure-text-minimessage:4.26.1")
	implementation ("net.kyori:adventure-text-serializer-gson:4.17.0")
	implementation ("net.kyori:adventure-text-serializer-legacy:4.17.0")
	implementation ("net.kyori:adventure-api:4.24.0")

	includeInternal ("net.kyori:adventure-text-minimessage:4.26.1")
	includeInternal ("net.kyori:adventure-text-serializer-gson:4.17.0")
	includeInternal ("net.kyori:adventure-text-serializer-legacy:4.17.0")
	includeInternal ("net.kyori:adventure-api:4.24.0")

	//modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}